### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by pamtaro** [microsoft/electionguard-tracking-site#38]
Running `yarn test` or `npm run test` results in the following error due to issues between FluentUI and Jest:
```
 /var/code/microsoft/electionguard-tracking-site/node_modules/office-ui-fabric-react/lib/Icon.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './components/Icon/index';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React from 'react';
    > 2 | import { FontIcon } from 'office-ui-fabric-react/lib/Icon';
        | ^
      3 | import { mergeStyles } from 'office-ui-fabric-react/lib/Styling';
      4 | import { IPalette, Stack, Text } from '@fluentui/react';
      5 | import { useTheme } from '@fluentui/react-theme-provider';

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/components/StatusMessage.tsx:2:1)
```

**Comment by BundiB** [comment]
is this being looked into?
